statusmessage.status_type.*:
  type: config_entity
  label: 'Status type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    media:
      type: boolean
      label: 'media'
    mime:
      type: string
      label: 'mime'
    uuid:
      type: string
