<?php

/**
 * @file
 * Contains statusmessage.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function statusmessage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the statusmessage module.
    case 'help.page.statusmessage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Status Messages on a User Profile Timeline') . '</p>';
      return $output;

    default:
  }
}
